version: '3'
services:
  src:
    container_name: full_app
    build: .
    command: ["go", "run", "main.go"]
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - ./src:/usr/share/src/files/compracliente.sql
      - ./src:/usr/share/src/files/tmp_compracliente.sql
    depends_on:
      - fullstack-postgres      
    networks:
      - fullstack


  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=CompraCliente
      - DATABASE_HOST=127.0.0.1
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: luiznd@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - fullstack-postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped


volumes:
  src: 
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge